version: '2'
services:
    uberhaupt-app:
        image: uberhaupt
        external_links:
            - uberhaupt-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=uberhaupt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uberhaupt-mongodb:
        extends:
            file: mongodb.yml
            service: uberhaupt-mongodb
