version: '2'
services:
    uberhaupt-mongodb:
        container_name: uberhaupt-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/uberhaupt/mongodb/:/data/db/
